<a href="https://colab.research.google.com/github/luiss1n/Teste-Faculdade./blob/main/Matriz%20inversa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
A = np.array([
    [3 , 2, 1],
    [2, 1 ,2],
    [3, 3, 4]
])

det_A = np.linalg.det(A)
print(int(det_A))

if det_A != 0:
  Inv_A = np.linalg.inv(A)
  print(Inv_A)
else :
  print("Matriz não tem inversa")


-6
[[ 0.28571429  0.71428571 -0.42857143]
 [ 0.28571429 -1.28571429  0.57142857]
 [-0.42857143  0.42857143  0.14285714]]
