<a href="https://colab.research.google.com/github/luiss1n/Teste-Faculdade./blob/main/Teste_Faculdade0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

Z = np.zeros((4, 4))
print(Z)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
